// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package backend

import (
	"github.com/99designs/gqlgen/graphql"
)

type FileUpload struct {
	File graphql.Upload `json:"file"`
	Name string         `json:"name"`
}
